<a href="https://colab.research.google.com/github/drago467/AIVN-MODULE-2/blob/main/Na%C3%AFve%20Bayes%20classifier%20(Classification)/1_Gaussian_Naive_Bayes_1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Gaussian Naive Bayes

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

import pandas as pd

iris = pd.read_csv('iris_1D.csv')

# Seperating the data into dependent and independent variables
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:, -1].values

In [ ]:
X_train[:,0]

array([1.4, 1. , 1.3, 1.9, 2. , 3.8, 4.1, 3.9, 4.2, 3.4])

In [ ]:
y_train

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [ ]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [ ]:
# predict
x_test = np.array([[3.0]])
clf.predict_proba(x_test)

array([[0.0454125, 0.9545875]])

In [ ]:
clf.class_count_

array([5., 5.])

In [ ]:
clf.class_prior_

array([0.5, 0.5])

In [ ]:
clf.classes_

array([0., 1.])

In [ ]:
clf.var_

array([[0.1416],
       [0.0776]])

In [ ]:
clf.theta_

array([[1.52],
       [3.88]])

## Compute manually

In [ ]:
import math
import numpy as np

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [ ]:
# compute Gaussian for group 1
data_c0 = np.array([1.4, 1.0, 1.3, 1.9, 2.0])
mean_c0 = data_c0.mean()
var_c0  = data_c0.var()

In [ ]:
# compute Gaussian for group 2
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
var_c1  = data_c1.var()
prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)

In [ ]:
# predict manually
x_test = np.array([[3.0]])
pdf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
pdf_c1_x = gaussian_function(x_test, mean_c1, var_c1)

# normalize
total = pdf_c0_x*0.5 + pdf_c1_x*0.5

pdf_c0_x = pdf_c0_x*0.5/total
pdf_c1_x = pdf_c1_x*0.5/total
print(pdf_c0_x)
print(pdf_c1_x)

[[0.00510668]]
[[0.0454125]]
[[0.9545875]]
