<a href="https://colab.research.google.com/github/drago467/AIVN-MODULE-2/blob/main/Na%C3%AFve%20Bayes%20classifier%20(Classification)/3_Gaussian_Naive_Bayes_2D_3C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Gaussian Naive Bayes

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

import pandas as pd

iris = pd.read_csv('iris_2D_3C.csv')

# Seperating the data into dependent and independent variables
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:, -1].values

In [ ]:
X_train

array([[4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [6.4, 3.2],
       [6.9, 3.1],
       [5.5, 2.3],
       [6.5, 2.8],
       [5.7, 2.8],
       [6.3, 3.3],
       [5.6, 2.2],
       [5.1, 1.5],
       [5.6, 1.4],
       [5.9, 2.1],
       [5.3, 1.8],
       [5.7, 1.9]])

In [ ]:
X_train[:,1]

array([3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3])

In [ ]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64)

In [ ]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [ ]:
# predict
x_test = np.array([[5.2, 2.4]])
clf.predict_proba(x_test)

array([[0.0418694 , 0.19180669, 0.76632391]])

In [ ]:
clf.class_prior_

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
clf.var_

array([[0.07888889, 0.09555556],
       [0.22805556, 0.11138889],
       [0.06888889, 0.08472222]])

In [ ]:
clf.theta_

array([[4.86666667, 3.36666667],
       [6.21666667, 2.91666667],
       [5.53333333, 1.81666667]])