<a href="https://colab.research.google.com/github/drago467/AIVN-MODULE-2/blob/main/Programming%20with%20high%20level%20syntax%20numpy%2C%201d%20data/convert_color.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### apply_along_axis

In [ ]:
import numpy as np

data = np.arange(9).reshape((3,3))
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
result0 = np.apply_along_axis(np.max, arr=data, axis=0)
print(result0)

[6 7 8]


In [ ]:
result1 = np.apply_along_axis(np.max, arr=data, axis=1)
print(result1)

[2 5 8]


In [ ]:
import numpy as np

def my_sum(vector):
    return vector.sum()

data = np.arange(9).reshape((3,3))
print(data)

result0 = np.apply_along_axis(my_sum,
                              arr=data, axis=0)
print(result0)

result1 = np.apply_along_axis(my_sum,
                              arr=data, axis=1)
print(result1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
[ 3 12 21]


### For Images

In [ ]:
# way 1

import cv2
import numpy as np

# Read the image
image = cv2.imread('image_color.png', 1)

def color2grayscale(vector):
    return vector[0]*0.3 + vector[1]*0.59 + vector[2]*0.11

# Convert
grayscale_image = np.apply_along_axis(color2grayscale, axis=2, arr=image)

# Save the grayscale image
cv2.imwrite('output1.png', grayscale_image)


True

In [ ]:
# way 2

import cv2
import numpy as np

# Read the image
image = cv2.imread('image_color.png', 1)

def color2grayscale(vector):
    return vector[0]*0.33 + vector[1]*0.33 + vector[2]*0.34

# Convert to grayscale
grayscale_image = np.apply_along_axis(color2grayscale,
                                      axis=2,
                                      arr=image)

# Save the grayscale image
cv2.imwrite('output2.png', grayscale_image)


True

In [ ]:
# way 3

import cv2
import numpy as np

# Read the image
image = cv2.imread('image_color.png', 1)

def color2grayscale(vector):
    result = vector.mean()
    result = result.astype(np.uint8)
    return result

# Convert
grayscale_image = np.apply_along_axis(color2grayscale,
                                      axis=2,
                                      arr=image)

# Save the grayscale image
cv2.imwrite('output3.png', grayscale_image)


True