<a href="https://colab.research.google.com/github/drago467/AIVN-MODULE-2/blob/main/Basic%20Probability%20and%20AI/SimpleClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Simple Classification

In [ ]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

# Data: Studied (1 for Yes, 0 for No) and Result (1 for Pass, 0 for Fail)
X = np.array([[0], [0], [1], [1], [1], [0]])
y = np.array([0, 1, 0, 1, 1, 0])

# Create and train the model
model = BernoulliNB()
model.fit(X, y)

# Predict the result for a student who studied
new_data = np.array([[1]])
prediction = model.predict(new_data)
prediction_proba = model.predict_proba(new_data)

In [ ]:
prediction

array([1])

In [ ]:
prediction_proba

array([[0.4, 0.6]])

In [ ]:
np.exp(model.class_log_prior_)

array([0.5, 0.5])

In [ ]:
# Empirical log probability of features given a class, P(x_i|y)
np.exp(model.feature_log_prob_)

array([[0.4],
       [0.6]])